site_name:        LTspice.jl
repo_url:         https://github.com/cstook/LTspice.jl
site_description: Julia interface to LTspice.
site_author:      Chris Stook

theme: readthedocs

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- Installation: install.md
- Quickstart: quickstart.md
- API: api.md
- New API: newapi.md